### PR TITLE
Intruduce Travis

### PR DESCRIPTION
**Pull request by szepeviktor**
Let's call `check` `test`!

https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Default-Test-Script
https://docs.npmjs.com/cli/test

### CODE REVIEW

**Comment by szepeviktor** [comment]
@evanvosberg What should we do with the lazy for loops wracking the test?

**Comment by szepeviktor** [comment]
Modern jshint output

```
grunt default
Running "jsonlint:all" (jsonlint) task
>> 1 file lint free.

Running "jshint:dev" (jshint) task

   src/aes.js
     35 |        for (var i = 0; i < 256; i++) {
                            ^ 'i' is already defined.
     55 |            var t = (x8 * 0x1010101) ^ (x4 * 0x10001) ^ (x2 * 0x101) ^ (x * 0x1010100);
                           ^ 't' is already defined.
    103 |                    if (!(ksRow % keySize)) {
                                 ^ Confusing use of '!'.
    124 |                var ksRow = ksRows - invKsRow;
                                   ^ 'ksRow' is already defined.
    127 |                    var t = keySchedule[ksRow];
                                   ^ 't' is already defined.
    129 |                    var t = keySchedule[ksRow - 4];
                                   ^ 't' is already defined.
    133 |                    invKeySchedule[invKsRow] = t;
                                                        ^ 't' used out of scope.
    135 |                    invKeySchedule[invKsRow] = INV_SUB_MIX_0[SBOX[t >>> 24]] ^ INV_SUB_MIX_1[SBOX[(t >>> 16) & 0xff]] ^
                                                                           ^ 't' used out of scope.
    135 |                    invKeySchedule[invKsRow] = INV_SUB_MIX_0[SBOX[t >>> 24]] ^ INV_SUB_MIX_1[SBOX[(t >>> 16) & 0xff]] ^
                                                                                                            ^ 't' used out of scope.
    136 |                                               INV_SUB_MIX_2[SBOX[(t >>> 8) & 0xff]] ^ INV_SUB_MIX_3[SBOX[t & 0xff]];
                                                                            ^ 't' used out of scope.
    136 |                                               INV_SUB_MIX_2[SBOX[(t >>> 8) & 0xff]] ^ INV_SUB_MIX_3[SBOX[t & 0xff]];
                                                                                                                   ^ 't' used out of scope.
    154 |            var t = M[offset + 1];
                           ^ 't' is already defined.
    188 |            var t0 = ((SBOX[s0 >>> 24] << 24) | (SBOX[(s1 >>> 16) & 0xff] << 16) | (SBOX[(s2 >>> 8) & 0xff] << 8) | SBOX[s3 & 0xff]) ^ keySchedule[ksRow++];
                            ^ 't0' is already defined.
    189 |            var t1 = ((SBOX[s1 >>> 24] << 24) | (SBOX[(s2 >>> 16) & 0xff] << 16) | (SBOX[(s3 >>> 8) & 0xff] << 8) | SBOX[s0 & 0xff]) ^ keySchedule[ksRow++];
                            ^ 't1' is already defined.
    190 |            var t2 = ((SBOX[s2 >>> 24] << 24) | (SBOX[(s3 >>> 16) & 0xff] << 16) | (SBOX[(s0 >>> 8) & 0xff] << 8) | SBOX[s1 & 0xff]) ^ keySchedule[ksRow++];
                            ^ 't2' is already defined.
    191 |            var t3 = ((SBOX[s3 >>> 24] << 24) | (SBOX[(s0 >>> 16) & 0xff] << 16) | (SBOX[(s1 >>> 8) & 0xff] << 8) | SBOX[s2 & 0xff]) ^ keySchedule[ksRow++];
                            ^ 't3' is already defined.
   src/cipher-core.js
    349 |                var block = this._prevBlock;
                                   ^ 'block' is already defined.
    354 |                words[offset + i] ^= block[i];
                                              ^ 'block' used out of scope.
    453 |                var modeCreator = mode.createDecryptor;
                                         ^ 'modeCreator' is already defined.
    458 |            if (this._mode && this._mode.__creator == modeCreator) {
                                                               ^ 'modeCreator' used out of scope.
    461 |                this._mode = modeCreator.call(mode, this, iv && iv.words);
                                      ^ 'modeCreator' used out of scope.
    462 |                this._mode.__creator = modeCreator;
                                                ^ 'modeCreator' used out of scope.
    483 |                var finalProcessedBlocks = this._process(!!'flush');
                                                  ^ 'finalProcessedBlocks' is already defined.
    489 |            return finalProcessedBlocks;
                            ^ 'finalProcessedBlocks' used out of scope.
    583 |                var wordArray = ciphertext;
                                       ^ 'wordArray' is already defined.
    586 |            return wordArray.toString(Base64);
                            ^ 'wordArray' used out of scope.
    619 |            return CipherParams.create({ ciphertext: ciphertext, salt: salt });
                                                                                ^ 'salt' used out of scope.
    862 |}());
            ^ Expected an assignment or function call and instead saw an expression.
   src/core.js
      9 |        function F() {};
                                ^ Unnecessary semicolon.
    179 |            if (sigBytes != undefined) {
                                  ^ Use '!==' to compare with 'undefined'.
    233 |                for (var i = 0; i < thatSigBytes; i += 4) {
                                    ^ 'i' is already defined.
    293 |                var m_w = m_w;
                                 ^ 'm_w' is already defined.
    303 |                    return result * (Math.random() > .5 ? 1 : -1);
                                                                ^ A leading decimal point can be confused with a dot: '.5'.
    292 |            var r = (function (m_w) {
                             ^ Wrapping non-IIFE function literals in parens is unnecessary.
    579 |            return new WordArray.init(processedWords, nBytesReady);
                                               ^ 'processedWords' used out of scope.
    461 |                return decodeURIComponent(escape(Latin1.stringify(wordArray)));
                                                   ^ 'escape' is not defined.
    481 |            return Latin1.parse(unescape(encodeURIComponent(utf8Str)));
                                         ^ 'unescape' is not defined.
   src/evpkdf.js
     75 |                var block = hasher.update(password).finalize(salt);
                                   ^ 'block' was used before it was defined.
   src/lib-typedarrays.js
     18 |        if (typedArray instanceof ArrayBuffer) {
                                           ^ 'ArrayBuffer' is not defined.
     19 |            typedArray = new Uint8Array(typedArray);
                                      ^ 'Uint8Array' is not defined.
     24 |            typedArray instanceof Int8Array ||
                                           ^ 'Int8Array' is not defined.
     25 |            (typeof Uint8ClampedArray !== "undefined" && typedArray instanceof Uint8ClampedArray) ||
                                                                                        ^ 'Uint8ClampedArray' is not defined.
     26 |            typedArray instanceof Int16Array ||
                                           ^ 'Int16Array' is not defined.
     27 |            typedArray instanceof Uint16Array ||
                                           ^ 'Uint16Array' is not defined.
     28 |            typedArray instanceof Int32Array ||
                                           ^ 'Int32Array' is not defined.
     29 |            typedArray instanceof Uint32Array ||
                                           ^ 'Uint32Array' is not defined.
     30 |            typedArray instanceof Float32Array ||
                                           ^ 'Float32Array' is not defined.
     31 |            typedArray instanceof Float64Array
                                           ^ 'Float64Array' is not defined.
     33 |            typedArray = new Uint8Array(typedArray.buffer, typedArray.byteOffset, typedArray.byteLength);
                                      ^ 'Uint8Array' is not defined.
     37 |        if (typedArray instanceof Uint8Array) {
                                           ^ 'Uint8Array' is not defined.
   src/mode-cfb.js
     47 |            var keystream = this._prevBlock;
                                   ^ 'keystream' is already defined.
     49 |        cipher.encryptBlock(keystream, 0);
                                     ^ 'keystream' used out of scope.
     53 |            words[offset + i] ^= keystream[i];
                                          ^ 'keystream' used out of scope.
   src/rabbit-legacy.js
     51 |            for (var i = 0; i < 8; i++) {
                                ^ 'i' is already defined.
     79 |                for (var i = 0; i < 4; i++) {
                                    ^ 'i' is already defined.
    135 |        for (var i = 0; i < 8; i++) {
                            ^ 'i' is already defined.
   src/rabbit.js
     48 |            for (var i = 0; i < 4; i++) {
                                ^ 'i' is already defined.
     53 |            for (var i = 0; i < 8; i++) {
                                ^ 'i' is already defined.
     81 |                for (var i = 0; i < 4; i++) {
                                    ^ 'i' is already defined.
    137 |        for (var i = 0; i < 8; i++) {
                            ^ 'i' is already defined.
   src/rc4.js
     25 |            for (var i = 0, j = 0; i < 256; i++) {
                                ^ 'i' is already defined.
   src/ripemd160.js
     91 |            for (var i = 0; i < 80; i += 1) {
                                ^ 'i' is already defined.
   src/sha256.js
     18 |                if (!(n % factor)) {
                             ^ Confusing use of '!'.
   src/sha3.js
     30 |        for (var x = 0; x < 5; x++) {
                            ^ 'x' is already defined.
     31 |            for (var y = 0; y < 5; y++) {
                                ^ 'y' is already defined.
    132 |                        var lane = state[x + 5 * y];
                                          ^ 'lane' is already defined.
    142 |                for (var x = 0; x < 5; x++) {
                                    ^ 'x' is already defined.
    150 |                    var tMsw = Tx4.high ^ ((Tx1Msw << 1) | (Tx1Lsw >>> 31));
                                      ^ 'tMsw' is already defined.
    151 |                    var tLsw = Tx4.low  ^ ((Tx1Lsw << 1) | (Tx1Msw >>> 31));
                                      ^ 'tLsw' is already defined.
    152 |                    for (var y = 0; y < 5; y++) {
                                        ^ 'y' is already defined.
    153 |                        var lane = state[x + 5 * y];
                                          ^ 'lane' is already defined.
    162 |                    var lane = state[laneIndex];
                                      ^ 'lane' is already defined.
    169 |                        var tMsw = (laneMsw << rhoOffset) | (laneLsw >>> (32 - rhoOffset));
                                          ^ 'tMsw' is already defined.
    170 |                        var tLsw = (laneLsw << rhoOffset) | (laneMsw >>> (32 - rhoOffset));
                                          ^ 'tLsw' is already defined.
    172 |                        var tMsw = (laneLsw << (rhoOffset - 32)) | (laneMsw >>> (64 - rhoOffset));
                                          ^ 'tMsw' is already defined.
    173 |                        var tLsw = (laneMsw << (rhoOffset - 32)) | (laneLsw >>> (64 - rhoOffset));
                                          ^ 'tLsw' is already defined.
    178 |                    TPiLane.high = tMsw;
                                            ^ 'tMsw' used out of scope.
    179 |                    TPiLane.low  = tLsw;
                                            ^ 'tLsw' used out of scope.
    189 |                for (var x = 0; x < 5; x++) {
                                    ^ 'x' is already defined.
    190 |                    for (var y = 0; y < 5; y++) {
                                        ^ 'y' is already defined.
    192 |                        var laneIndex = x + 5 * y;
                                               ^ 'laneIndex' is already defined.
    193 |                        var lane = state[laneIndex];
                                          ^ 'lane' is already defined.
    205 |                var lane = state[0];
                                  ^ 'lane' is already defined.
    208 |                lane.low  ^= roundConstant.low;;
                                                        ^ Unnecessary semicolon.
   src/sha512.js
    161 |                    var Wil = gamma0l + Wi7l;
                                     ^ 'Wil' is already defined.
    162 |                    var Wih = gamma0h + Wi7h + ((Wil >>> 0) < (gamma0l >>> 0) ? 1 : 0);
                                     ^ 'Wih' is already defined.
    163 |                    var Wil = Wil + gamma1l;
                                     ^ 'Wil' is already defined.
    164 |                    var Wih = Wih + gamma1h + ((Wil >>> 0) < (gamma1l >>> 0) ? 1 : 0);
                                     ^ 'Wih' is already defined.
    165 |                    var Wil = Wil + Wi16l;
                                     ^ 'Wil' is already defined.
    166 |                    var Wih = Wih + Wi16h + ((Wil >>> 0) < (Wi16l >>> 0) ? 1 : 0);
                                     ^ 'Wih' is already defined.
    189 |                var t1l = t1l + chl;
                                 ^ 't1l' is already defined.
    190 |                var t1h = t1h + chh + ((t1l >>> 0) < (chl >>> 0) ? 1 : 0);
                                 ^ 't1h' is already defined.
    191 |                var t1l = t1l + Kil;
                                 ^ 't1l' is already defined.
    192 |                var t1h = t1h + Kih + ((t1l >>> 0) < (Kil >>> 0) ? 1 : 0);
                                 ^ 't1h' is already defined.
    193 |                var t1l = t1l + Wil;
                                 ^ 't1l' is already defined.
    193 |                var t1l = t1l + Wil;
                                         ^ 'Wil' used out of scope.
    194 |                var t1h = t1h + Wih + ((t1l >>> 0) < (Wil >>> 0) ? 1 : 0);
                                 ^ 't1h' is already defined.
    194 |                var t1h = t1h + Wih + ((t1l >>> 0) < (Wil >>> 0) ? 1 : 0);
                                         ^ 'Wih' used out of scope.
    194 |                var t1h = t1h + Wih + ((t1l >>> 0) < (Wil >>> 0) ? 1 : 0);
                                                               ^ 'Wil' used out of scope.
   src/tripledes.js
    599 |                for (var i = 0; i < 24; i++) {
                                    ^ 'i' is already defined.
    611 |                for (var i = 1; i < 7; i++) {
                                    ^ 'i' is already defined.
    619 |            for (var i = 0; i < 16; i++) {
                                ^ 'i' is already defined.
   src/x64-core.js
    228 |            if (sigBytes != undefined) {
                                  ^ Use '!==' to compare with 'undefined'.

>> 103 errors in 41 files
Warning: Task "jshint:dev" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by szepeviktor** [comment]
@evanvosberg Thanks.
Could you enable Travis for this repo?

**Comment by evanvosberg** [comment]
Did so and updated the code to pass the tests.

**Pull request merged**
