### PR TITLE
Bower support

### PR DESCRIPTION
**Pull request by kirill-konshin**
Added bower.json file
Added .npmignore for easier NPM publish
Modified package.json file
Commented out cleanup after build procedure (files are needed for Bower and NPM)

Unfortunately, NPM publish directly from repository is not yet possible:

``` js
require('crypto-js/build/crypto-js/lib-uncompressed/aes')
```

is very ugly and I don't want to break backward compatibility with

### CODE REVIEW

**Comment by kirill-konshin** [comment]
So for now NPM publish procedure will stay the same, unless I'll find a way to leave files in sub-folders and refer to them as before. Bower requires only pre-build and can be published without extra efforts.

In order to register Bower package please do:

``` sh
bower register crypto-js git://github.com/evanvosberg/crypto-js.git
```

For now package name `crypto-js` is not taken yet, so be quick :)

**Comment by kirill-konshin** [comment]
Looks like you use GitFlow, if needed, I can reapply my changes to develop branch.

**Comment by evanvosberg** [comment]
You are right I use GitFlow so it's best to send pull request for develop branch.

Will have a look for your stuff in the next days ;)

**Comment by kirill-konshin** [comment]
Created follow up PR https://github.com/evanvosberg/crypto-js/pull/21

**Pull request closed without merging**
