### PR TITLE
feat: add urlsafe

### PR DESCRIPTION
**Pull request by spencer17x**
issue：https://github.com/brix/crypto-js/issues/252

### CODE REVIEW

**Comment by kylelieTomo** [comment]
and this update makes crypto doesn't work on ie11

**Comment by spencer17x** [comment]
Are you sure it is affected by this pr? Can you provide some information? If it is determined that it is affected by pr, you can delete this method if you don't need url-safe. @kylelieTomo

**Comment by kylelieTomo** [comment]
yes, ie11 doesn't support default value on params. and the "urlSafe=true" affect ie

**Comment by spencer17x** [comment]
Maybe this repo does not configure the corresponding babel, you can clone in the past and configure the corresponding babel yourself

**Comment by trmpowell** [comment]
@kylelieTomo, were you able to get this working in IE 11?

**Comment by kylelieTomo** [comment]
> @kylelieTomo, were you able to get this working in IE 11?

no, i just fall back to 4.0.0

**Comment by trmpowell** [comment]
@Spencer17x, do you have any plans to resolve this? Permanently falling back to an old version isn't ideal as consumers wouldn't be able to get new security fixes in future versions.

**Comment by spencer17x** [comment]
@trmpowell The author of this library is not me. If I fix it, I need to mention pr. I am not sure when the author will merge. If you need it, I can fork it and maintain it.

**Comment by spencer17x** [comment]
@trmpowell Hello, I used this pr to fix the problem you raised, but I need to wait for the author to merge, and I may fork this repo and use other build tools to maintain it in the future.

**Comment by trmpowell** [comment]
Thanks, @Spencer17x! No problem on needing to wait for the repo owner to merge. That is expected. 😃

**Comment by Mehmdsed** [comment]
Android

**Comment by Mehmdsed** [comment]
Wifi

**Pull request merged**
