### PR TITLE
Check existence of Uint8ClampedArray for IE10 compatibility

### PR DESCRIPTION
**Pull request by tqc**

### CODE REVIEW

**Comment by evanvosberg** [comment]
Please change the target branch of your pull request to `master`.

**Comment by tqc** [comment]
Looks like it already is - I see

```
tqc  wants to merge 1 commit into evanvosberg:master
```

**Comment by evanvosberg** [comment]
sorry my fault `develop` I mean

**Comment by tqc** [comment]
Done as a new pull request - apparently the target branch isn't updatable

**Pull request closed without merging**
